"""Initial migration

Revision ID: 9ae94f0fcc4e
Revises: 
Create Date: 2026-01-14 03:14:09.856358-03:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9ae94f0fcc4e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_state',
    sa.Column('alert_type', sa.String(length=50), nullable=False, comment='Unique alert type identifier (e.g., FAILED_THRESHOLD)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='True if alert is currently active, False if resolved'),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when alert was last detected'),
    sa.Column('last_resolved_at', sa.DateTime(timezone=True), nullable=True, comment='Timestamp when alert was last resolved'),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='Identificador único'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id'),
    comment='Stores alert states for anti-spam and reactivation logic'
    )
    op.create_index('idx_alert_state_alert_type', 'alert_state', ['alert_type'], unique=True)
    op.create_index(op.f('ix_alert_state_alert_type'), 'alert_state', ['alert_type'], unique=True)
    op.create_table('companies',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único UUID de la empresa'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='Nombre de la empresa'),
    sa.Column('tax_id', sa.String(length=50), nullable=True, comment='RUT o identificador tributario'),
    sa.Column('description', sa.Text(), nullable=True, comment='Descripción de la empresa'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Empresa activa o desactivada'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_companies_tax_id'), 'companies', ['tax_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único UUID del usuario'),
    sa.Column('email', sa.String(length=255), nullable=False, comment='Email del usuario (usado para login)'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment='Nombre completo del usuario'),
    sa.Column('password_hash', sa.String(length=255), nullable=True, comment='Hash de contraseña (implementación futura)'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='Usuario activo o desactivado'),
    sa.Column('is_superuser', sa.Boolean(), nullable=False, comment='Usuario administrador del sistema'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('changed_by', sa.UUID(), nullable=True),
    sa.Column('before_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_logs_company_id', 'audit_logs', ['company_id'], unique=False)
    op.create_index('idx_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('idx_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('idx_audit_logs_entity_type', 'audit_logs', ['entity_type'], unique=False)
    op.create_table('company_users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification_queue',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único de la notificación'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Empresa asociada'),
    sa.Column('channel', sa.String(length=50), nullable=False, comment='Canal de envío (telegram/email)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Contenido de la notificación (formato flexible)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Estado (pending/sent/failed)'),
    sa.Column('scheduled_for', sa.DateTime(timezone=True), nullable=False, comment='Fecha y hora programada para envío'),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True, comment='Fecha y hora de envío efectivo'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_queue_company_id'), 'notification_queue', ['company_id'], unique=False)
    op.create_index(op.f('ix_notification_queue_scheduled_for'), 'notification_queue', ['scheduled_for'], unique=False)
    op.create_index(op.f('ix_notification_queue_status'), 'notification_queue', ['status'], unique=False)
    op.create_table('notification_settings',
    sa.Column('id', sa.UUID(), nullable=False, comment='Identificador único de configuración'),
    sa.Column('company_id', sa.UUID(), nullable=False, comment='Empresa asociada (1:1)'),
    sa.Column('telegram_enabled', sa.Boolean(), nullable=False, comment='Notificaciones vía Telegram habilitadas'),
    sa.Column('telegram_chat_id', sa.String(), nullable=True, comment='Chat ID de Telegram para envío'),
    sa.Column('email_enabled', sa.Boolean(), nullable=False, comment='Notificaciones vía email habilitadas'),
    sa.Column('email_to', sa.String(), nullable=True, comment='Email destinatario'),
    sa.Column('daily_summary_time', sa.Time(), nullable=False, comment='Hora diaria para envío de resumen (HH:MM)'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de creación del registro'),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False, comment='Fecha de última actualización'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('recurring_templates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('total_installments', sa.Integer(), nullable=False),
    sa.Column('installments_paid_before', sa.Integer(), nullable=False),
    sa.Column('installment_amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('start_control_date', sa.Date(), nullable=False),
    sa.Column('autopay_enabled', sa.Boolean(), nullable=False),
    sa.Column('autopay_day', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('autopay_day IS NULL OR (autopay_day >= 1 AND autopay_day <= 28)', name='check_autopay_day_range'),
    sa.CheckConstraint('autopay_enabled = true OR autopay_day IS NULL', name='check_autopay_day_requires_enabled'),
    sa.CheckConstraint('installments_paid_before <= total_installments', name='check_installments_paid_before_lte_total'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('company_id', sa.UUID(), nullable=False),
    sa.Column('template_id', sa.UUID(), nullable=True),
    sa.Column('installment_number', sa.Integer(), nullable=True),
    sa.Column('installment_total', sa.Integer(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('autopay', sa.Boolean(), nullable=False),
    sa.Column('payment_method', sa.String(), nullable=True),
    sa.Column('payment_reference', sa.String(), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("status IN ('pending', 'scheduled', 'paid', 'overdue')", name='check_status_valid'),
    sa.CheckConstraint('installment_number IS NULL OR (installment_number >= 1 AND installment_number <= installment_total)', name='check_installment_number_in_range'),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['template_id'], ['recurring_templates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id', 'template_id', 'installment_number', name='unique_company_template_installment')
    )
    op.create_index('idx_payments_company_id', 'payments', ['company_id'], unique=False)
    op.create_index('idx_payments_due_date', 'payments', ['due_date'], unique=False)
    op.create_index('idx_payments_status', 'payments', ['status'], unique=False)
    op.create_index('idx_payments_template_id', 'payments', ['template_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_payments_template_id', table_name='payments')
    op.drop_index('idx_payments_status', table_name='payments')
    op.drop_index('idx_payments_due_date', table_name='payments')
    op.drop_index('idx_payments_company_id', table_name='payments')
    op.drop_table('payments')
    op.drop_table('recurring_templates')
    op.drop_table('notification_settings')
    op.drop_index(op.f('ix_notification_queue_status'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_scheduled_for'), table_name='notification_queue')
    op.drop_index(op.f('ix_notification_queue_company_id'), table_name='notification_queue')
    op.drop_table('notification_queue')
    op.drop_table('company_users')
    op.drop_index('idx_audit_logs_entity_type', table_name='audit_logs')
    op.drop_index('idx_audit_logs_entity_id', table_name='audit_logs')
    op.drop_index('idx_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('idx_audit_logs_company_id', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_companies_tax_id'), table_name='companies')
    op.drop_table('companies')
    op.drop_index(op.f('ix_alert_state_alert_type'), table_name='alert_state')
    op.drop_index('idx_alert_state_alert_type', table_name='alert_state')
    op.drop_table('alert_state')
    # ### end Alembic commands ###
